### ISSUE TITLE
PolyConfig Crashes with this port

### ISSUE THREAD

**Issue by fennecr** [skerit/PolyMc#3]
Functions correctly until you put anything in the PolyConfig file. Server crashes with this exception:

```[03:08:06] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void net.minecraft.class_2960.<init>(java.lang.String)'
        at nl.theepicblock.polyconfig.Utils.getFromRegistry(Utils.java:66) ~[polyconfig-0.3.7.i0:0/:?]
        at nl.theepicblock.polyconfig.block.BlockNodeParser.parseBlockNode(BlockNodeParser.java:20) ~[polyconfig-0.3.7.i0:0/:?]
        at nl.theepicblock.polyconfig.PolyConfig.handleFile(PolyConfig.java:107) ~[polyconfig-0.3.7.i0:0/:?]
        at nl.theepicblock.polyconfig.PolyConfig.lambda$registerPolys$0(PolyConfig.java:64) ~[polyconfig-0.3.7.i0:0/:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:601) ~[?:?]
        at nl.theepicblock.polyconfig.PolyConfig.registerPolys(PolyConfig.java:62) ~[polyconfig-0.3.7.i0:0/:?]
        at io.github.theepicblock.polymc.PolyMc.generatePolyMap(PolyMc.java:75) ~[polymc-5.7.01.21.i0:0/:?]
        at io.github.theepicblock.polymc.PolyMc.onRegistryClosed(PolyMc.java:62) ~[polymc-5.7.01.21.i0:0/:?]
        at net.minecraft.server.MinecraftServer.handler$dhl000$polymc$createWorlds(MinecraftServer.java:13129) ~[transformed-mod-minecraft-v1.21.jar:?]
        at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java) ~[transformed-mod-minecraft-v1.21.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:342) ~[transformed-mod-minecraft-v1.21.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:185) ~[transformed-mod-minecraft-v1.21.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:664) ~[transformed-mod-minecraft-v1.21.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[transformed-mod-minecraft-v1.21.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]```

**Comment by skerit** [comment]
@fennecr PolyConfig has not been updated to 1.21 yet. This error is just because of the Identifier changes (`new Identifier()` calls are no longer possible). If it's only that, it shouldn't be too hard to upgrade. However: I don't use PolyConfig and have a ton on my plate already, so someone else will have to pick that up.

**Comment by fennecr** [comment]
I realized this after commenting and then updated polyconfig myself. oops, sorry!!
